### ISSUE TITLE
[feat request] Cannot get systemCoordinator from new session

### ISSUE THREAD

**Issue by milanow** [Pixeland-Tech/SharePlayMock#3]
I know "However it does NOT help with testing the logic of positioning participants." from [tutorial](https://medium.com/@xinyichen0321/the-easiest-way-to-test-shareplay-on-visionos-apps-7bf8a1753d8e)
. But can I still get at least a mocked systemCoordinator from session? Nowadays I believe most of the applications are developed on xrOS 2 to leverage the new APIs like TabletopKit or CustomTemplate. 

A mocked SystemCoordinator would help a lot to avoid intrusive code.

**Comment by ymaxli** [comment]
We're working on this. Thanks for the suggestion!

**Comment by xinyic** [comment]
v0.1.2 has been updated with a SystemCoordinatorMock. Hope this can reduce some intrusive code.
